dist: trusty
language: java
jdk:
    - openjdk8
cache:
    directories:
    - "$HOME/.m2"
install:
    - curl -o $HOME/.m2/settings.xml https://raw.githubusercontent.com/trajano/trajano/master/src/site/resources/settings.xml
    - mvn dependency:go-offline
script: mvn clean install